### ISSUE TITLE
Setup automation

### ISSUE THREAD

**Issue by parzhitsky** [parzh/retryable#15]
##### (actions [`"opened"`], [`"labeled"`], [`"unlabeled"`])
- [ ] require exactly one `"Change: (major|minor|patch)"` label

##### (action [`"synchronize"`])
- [ ] `npm run build`
- [ ] `npm test`
- [ ] `npm lint`

##### (action [`"closed"`], if<sup>[1][conditions]</sup> [`github.event.pull_request.merged`])
- [ ] collect release notes
- [ ] collect code coverage

***

### [`push`] &rarr; [`parzh:develop`]
- [ ] `npm run build`
- [ ] `npm test`
- [ ] `npm lint`

***

##### (actions [`"opened"`], [`"labeled"`], [`"unlabeled"`])
- [ ] require head to be `parzh:develop`
- [ ] require exactly one `"Change: (major|minor|patch)"` label

##### (actions [`"labeled"`], [`"unlabeled"`])
- [ ] gather semver change type
	```sh
	# show merge commits after latest merge to master
	git rev-list master..develop --merges
	```

##### (action [`"closed"`], if [`github.event.pull_request.merged`])
- [ ] require exactly one `"Change: (major|minor|patch)"` label
- [ ] `npm run build`
- [ ] `npm test`
- [ ] `npm run lint`
- [ ] `npm version $VERSION_SPECIFIED_BY_LABEL`
- [ ] `npm publish @next`
- [ ] reset `publish @latest` timer (see below)

***

### one week since the latest "publish @next"
- [ ] re-publish `@next` version as `@latest`

	```sh
	# get current @next version
	NEXT_VERSION="$(npm view @parzh/retryable@next --version)"

	# put @latest tag on @next release
	npm dist-tag add @parzh/retryable@$NEXT_VERSION latest
	```

  [`parzh:develop`]: /parzh/retryable/commits/develop
  [`parzh:master`]: /parzh/retryable/commits/master

  [`push`]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#push-event-push
  [`pull_request`]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request

  [conditions]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idif
  [`github.event.pull_request.merged`]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#github-context

  [`"synchronize"`]: https://gist.github.com/parzhitsky/bf0aa853802e6b7d510b5d36d920f015#file-main-yml-L18
  [`"opened"`]: https://gist.github.com/parzhitsky/bf0aa853802e6b7d510b5d36d920f015#file-main-yml-L10
  [`"closed"`]: https://gist.github.com/parzhitsky/bf0aa853802e6b7d510b5d36d920f015#file-main-yml-L11
  [`"labeled"`]: https://gist.github.com/parzhitsky/bf0aa853802e6b7d510b5d36d920f015#file-main-yml-L7
  [`"unlabeled"`]: https://gist.github.com/parzhitsky/bf0aa853802e6b7d510b5d36d920f015#file-main-yml-L8

**Comment by parzhitsky** [comment]
Converted to the **[Automated releases](https://github.com/parzh/retryable/milestone/1)** milestone
