### ISSUE TITLE
Build, test, and lint changes

### ISSUE THREAD

**Issue by parzhitsky** [parzh/retryable#27]
Build (`npm run build`), test (`npm test`), and lint (`npm run lint`) changes, when:
- [x] updating the `develop` branch;
- [x] opening or updating a PR to `develop`;
- [ ] merging a PR to `master`;

**Comment by parzhitsky** [comment]
Blocked by #22

**Comment by parzhitsky** [comment]
Reopen due to the incomplete third task

**Comment by parzhitsky** [comment]
The third task extracted to #37
